### ISSUE TITLE
Concept classes

### ISSUE THREAD

**Issue by dr-shorthair** [surroundaustralia/fsdf-kg#5]
Where the range of a property is `skos:Concept` it is useful to also define a sub-class of `skos:Concept` to better constrain/define the target. e.g. RelationToGround, Theme, OperationalStatus

**Comment by nicholascar** [comment]
Implemented as suggested in Commit https://github.com/surroundaustralia/fsdf-kg/commit/0d57d68c42f84ba097822d85a0c880db93021627
